### ISSUE TITLE
Pipez

### ISSUE THREAD

**Issue by Ackimixs** [cfouche3005/ISEN-Tech#1]
Les câbles présent sont pas assez puissants et pour les reacteurs meka + turbine pour faire du steam il faut une entré d'eau fumé alors que les cables meka sont pas super puissant

il existe le mod pipez en 1.18 beaucoup utilisé qui permet de transféré sois liquid sois items sois energy avec des filtres assez cher donc pas trop pété qui permettent de transféré vraiment beaucoup et des filtrer autant d'item qu'on veux

Fin pipez est vraiment bien

**Comment by BreizhHardware** [comment]
Je vais rajouter le mods
Merci du retour
BreizhHardware développeur du modpack

**Comment by BreizhHardware** [comment]
L'update a été faites.
Bon jeu

**Comment by cfouche3005** [comment]
Attention, l'update au niveau du server n'ayant pas été faite, ne mettez pas à jour votre modpack et attendez l'annonce de l'update.
