### ISSUE TITLE
Implementation garden cloche + mystical

### ISSUE THREAD

**Issue by Ackimixs** [cfouche3005/ISEN-Tech#2]
Pour moins de lague tu peux crée des crafts customs avec immersive et faire des craft avec les graine mystical avec en dessous les differentes farmland comme ca c'est plus pratique

i can do it if u want

**Comment by BreizhHardware** [comment]
Je vais la faire cette après midi
Merci du retour
BreizhHardware développeur du modpack

**Comment by BreizhHardware** [comment]
L'update a été faites.
Bon jeu

**Comment by cfouche3005** [comment]
Attention, l'update au niveau du server n'ayant pas été faite, ne mettez pas à jour votre modpack et attendez l'annonce de l'update.
